export const USER_REGISTER="USER_REGISTER"
export const USER_LOGIN="USER_LOGIN"
export const USER_FAIL="USER_FAIL"
export const GET_USER="GET_USER"
export const SET_ALERT="SET_ALERT"
export const REMOVE_ALERT="REMOVE_ALERT"
export const LOGOUT="LOGOUT"


export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT= 'DELETE_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
